<?php


namespace app\controller\config;


use app\business\mysql\Backups;
use app\controller\Base;
use app\model\SysConfig as models;
use app\traits\PublicCrudTrait;
use think\facade\Db;
use think\exception\ValidateException;
use \app\validate\SysConfig as validates;

class SysConfig extends Base
{
    protected $model;
    use PublicCrudTrait;

    /**
     *配置控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件

        //->page($page, $limit)
        $list = $this->model->order('id desc')->select()->toArray();
        return $this->success($list);
    }

    /**
     * 添加
     */
    public function add()
    {
        //过滤数据
        $postField = 'name,value';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        //验证数据
        try {
            validate(validates::class)->scene('add')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        $user = $this->model->where('name',$post['name'])->find();
        if ($user) return $this->failed('该配置以存在');

        $save = $this->model->save($post);
        if ($save) return $this->success([]);
        return $this->failed('新增失败');
    }


    /**
     * 修改
     * @return mixed
     */
    public function edit()
    {
        //过滤数据
        $postField = 'id,name,value';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        //验证数据
        try {
            validate(validates::class)->scene('edit')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            return $this->failed($e->getError());
        }

        //查询是否重复的
        $find = $this->model->where('name', $post['name'])->where('id', '<>', $post['id'])->find();
        if ($find) return $this->failed('该配置以存在');

        //执行修改数据
        $save = $this->model->update($post);
        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }

    public function config_info()
    {
        $app_webchat= $this->request->post('name','');
        if (empty($app_webchat)) $this->failed('参数错误');
        $find = $this->model->where('name',$app_webchat)->find();
        if (empty($find)) return $this->failed();
        return $this->success($find);
    }

    public function clear_token()
    {
      Db::query('truncate ntp_common_home_token');
     return $this->success([]);
    }

    //备份露珠表
    public function mysql_backups()
    {
        $service = new Backups();
        $service->copy_table_lu_zhu('ntp_dianji_lu_zhu');
        return $this->success([]);
    }
    //备份下注表
    public function mysql_records()
    {
        $service = new Backups();
        $service->copy_table_order('ntp_dianji_records');
        return $this->success([]);
    }
}