<?php


namespace app\controller\desktop;

use app\controller\Base;

use app\model\Table as models;
use app\model\TableLangModel;
use app\traits\PublicCrudTrait;
use app\validate\TableValidate as validates;
use think\exception\ValidateException;


class Desktop extends Base
{
    protected $model;
    use PublicCrudTrait;

    /**
     * 桌面控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 100);
        //查询搜索条件
        $post = array_filter($this->request->post());
        $map = [];
        isset($post['table_title']) && $map [] = ['table_title', 'like', '%' . $post['table_title'] . '%'];

        $list = $this->model->page_list($map, $limit, $page);
         $this->success($list);
    }
    /**
     * 更新是否点击
     */
    public function updatedianji()
    {
        //过滤数据
        $postField = 'id,is_dianji';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        $save = $this->model->update($post);
        if ($save) $this->success([]);
        $this->failed('修改失败');
    }
    /**
     * 添加
     */
    public function add()
    {
        //过滤数据
        $post = $this->request->post();
        //验证数据
        try {
            validate(validates::class)->scene('add')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
             $this->failed($e->getError());
        }

        $user = $this->model->where('table_title', $post['table_title'])->find();
        if ($user)  $this->failed('该台桌以存在');
        //处理图片
       isset($post['he_guan_head_img']) && $post['he_guan_head_img']= image_update($post['he_guan_head_img']);
        $post['start_time'] =  strtotime($post['start_time']);
        $post['create_time'] = date('Y-m-d H:i:s');
        $post['update_time'] = date('Y-m-d H:i:s');
        $post['game_play_staus'] =$post['is_dianji']=$post['is_weitou']=$post['is_diantou']= 0;
        $save = $this->model->save($post);
        if ($save)  $this->success([]);
         $this->failed('新增失败');
    }



    /**
     * 修改
     * @return mixed
     */
    public function edit()
    {
        $post = $this->request->post();

        //验证数据
        try {
            validate(validates::class)->scene('edit')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
             $this->failed($e->getError());
        }

        //查询是否重复的该菜单
        $find = $this->model->where('table_title', $post['table_title'])->where('id', '<>', $post['id'])->find();
        if ($find)  $this->failed('该标题以存在');
        if (isset($post['he_guan_head_img']) && is_array($post['he_guan_head_img'])){
            $post['he_guan_head_img']= image_update($post['he_guan_head_img']);
        }
        $post['start_time'] =  strtotime($post['start_time']);
        //执行修改数据
        $save = $this->model->update($post);

        if ($save)  $this->success([]);
         $this->failed('修改失败');
    }
    /**
     * 查询
     * @return mixed
     */
    public function detail()
    {
        //过滤数据
        $postField = 'id';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        if (!isset($post['id']) || $post['id'] <= 0 ){
             $this->failed('ID不存在');
        }
        //查询
        $user = $this->model->find($post['id']);
        if ($user)  $this->success($user);
         $this->failed('文章不存在');
    }

    //根据游戏类型获取台座
    public function table_list()
    {
        $game_type = $this->request->param('game_type/d',0);
        if ($game_type <= 0) $this->failed('game_type参数错误');
        $list =$this->model->where('game_type',$game_type)->order('id asc')->paginate(['list_rows' => 100, 'page' => 1], false);
        $this->success($list);
    }

    //游戏规则多语言
    public function game_lang_list()
    {
        $post = $this->request->post();
        if (!isset($post['id']) || $post['id'] <= 0) $this->failed('ID必填');
        $info = TableLangModel::table_explain($post['id']);
        $this->success($info);
    }

    public function game_lang_edit()
    {
        $postField = 'id,zh,en,jp,kor,tha,vnm';//过滤数据
        $post = $this->request->only(explode(',', $postField), 'post', null);
        $post = array_filter($post);
        if (!isset($post['id']) || $post['id'] <= 0) $this->failed('ID必填');
        $id = $post['id'];
        unset($post['id']);
        try {
            foreach ($post as $key => $value) {
                $lang_type = $key;
                if ($key == 'zh') {
                    $find = TableLangModel::page_one(['table_id' => $id, 'lang_type' => 'zh-cn']);
                    $lang_type = 'zh-cn';
                } elseif ($key == 'en') {
                    $find = TableLangModel::page_one(['table_id' => $id, 'lang_type' => 'en-us']);
                    $lang_type = 'en-us';
                } else {
                    $find = TableLangModel::page_one(['table_id' => $id, 'lang_type' => $key]);
                }
                if (empty($find)) {//为空时插入数据
                    TableLangModel::set_insert(['table_id' => $id, 'lang_type' => $lang_type, 'explain' => $value]);
                    continue;
                }
                //非空时修改数据
                TableLangModel::set_update(['id' => $find->id, 'explain' => $value]);
                continue;
            }
        } catch (\Exception $e) {
            $this->failed($e->getMessage());// 这是进行异常捕获
        }
        $this->success([]);
    }

    public function del()
    {
        $id = $this->request->post('id', 0);
        if ($id < 1) $this->failed('ID错误');

        //模型删除
        $del = $this->model->where('id',$id)->update(['status'=>-1]);
        if ($del) $this->success([]);
        $this->failed('删除失败，数据不存在');
    }
    
        //限红开启关闭
    public function is_xh(){
        $id = $this->request->post('id', 0);
        if ($id < 1) $this->failed('ID错误');
        $is_xh = $this->request->post('is_xh', 0);
        //模型删除
        $del = $this->model->where('id',$id)->update(['is_table_xian_hong'=>$is_xh]);
        if ($del) $this->success([]);
        $this->failed('修改失败，数据不存在');
    }
}