<?php


namespace app\controller\desktop;

use app\controller\Base;

use app\model\Luzhu as models;
use app\traits\PublicCrudTrait;


class PrintLuzhu extends Base
{
    protected $model;
    use PublicCrudTrait;

    /**
     * 露珠控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {
        //查询搜索条件
        $post = array_filter($this->request->post());
        $map = $date = [];
        if (!isset($post['game_type']) || !isset($post['start']) || !isset($post['end'])){
            $this->failed('游戏类型,时间必填');
        };
        isset($post['table_id']) && $map [] = ['table_id', 'in', $post['table_id']];
        $map [] = ['game_type', '=', $post['game_type']];
        isset($post['xue']) && $map[] = ['xue_number', '=', $post['xue']];
        $map[] = ['status', '=', 1];
        $date['start'] = $post['start'];
        $date['end'] = $post['end'];
        $list = $this->model->print_list($map,  $date);
        $this->success($list);
    }

    //露珠打印数据
    public function printData()
    {
        //游戏类型、台座
        $game_type = $this->request->param('game_type/d', 0);
        if ($game_type <= 0) $this->failed('game_type参数错误');
        $table_id = $this->request->param('table_id/d', 0);
        if ($table_id <= 0) $this->failed('table_id参数错误');
        $map[] = ['table_id', '=', $table_id];
        $map[] = ['game_type', '=', $game_type];
        $xue = $this->request->param('xue/d', 0);
        if ($xue > 0) $map[] = ['xue_number', '=', $xue];

        $post = array_filter($this->request->post());
        $date = [];
        isset($post['create_date']) && $date['start'] = $post['create_date'].' 00:00:00';
        isset($post['create_date']) && $date['end'] = $post['create_date'].' 23:59:50';
        $limit = 180;
        $page = 0;
        $order = 'id asc';
        switch ($game_type) {
            case 1:
            case 3:
                $limit = 66;
                break;
        }
        //查询露珠
        $list = $this->model->page_list_print($map, $date, $limit, $page, $order);
        if (empty($list)) $this->success($list);

        $data = $this->model->luzhu_style($game_type, $list);
        $this->success($data);
    }
}