<?php


namespace app\controller\game;

use app\controller\Base;

use app\model\GameType;
use app\model\Odds as models;
use app\traits\PublicCrudTrait;

class Odds extends Base
{
    protected $model;
    use PublicCrudTrait;

    /**
     * 桌面控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 100);
        //查询搜索条件
        $post = array_filter($this->request->post());
        $map = [];
        isset($post['type_id']) && $map  = ['game_type_id'=>$post['type_id']];

        $list = $this->model->page_list($map, $limit, $page);
         $this->success($list);
    }

    /**
     * 添加
     */
    public function add()
    {
        $post = $this->request->post();
        $save = $this->model->save($post);
        if ($save)  $this->success([]);
         $this->failed('新增失败');
    }

    /**
     * 修改
     * @return mixed
     */
    public function edit()
    {
        $post = $this->request->post();
        if (!isset($post['id']) || $post['id'] <=0)  $this->failed('修改失败');
        //执行修改数据
        $save = $this->model->update($post);
        if ($save)  $this->success([]);
         $this->failed('修改失败');
    }
}