<?php


namespace app\controller\game;

use app\controller\Base;

use app\model\GameRecords as models;
use app\traits\PublicCrudTrait;
use app\traits\TraitModel;

class Profit extends Base
{
    protected $model;
    use PublicCrudTrait;
    /**
     * 盈亏排行榜
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post = ($this->request->post());
        $map = [];
        isset($post['user_name']) && $map[] = ['user_name', 'like', '%' . $post['user_name'] . '%'];
        if (isset($post['is_fictitious'])){
           $map[] = ['is_fictitious','=',$post['is_fictitious']];
        }else{
            $map[] = ['is_fictitious','=',0];
        }

        $date['start'] = date('Y-m-d').' 00:00:00';
        $date['end'] = date('Y-m-d').' 23:58:50';
        $list = $this->model->profit_list($map,$limit,$page,$date);
         $this->success($list);
    }
}
