<?php


namespace app\controller\game;

use app\controller\Base;

use app\model\UserModel as models;
use app\traits\GatUserAuthTrait;

class UserSort extends Base
{
    protected $model;
    use GatUserAuthTrait;

    /**
     * 用户提现排行，充值排行，可用余额排行
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 50);
        //查询搜索条件
        $post = $this->request->post();
        $map = [];
        $map[] = ['type', '=', 2];
        isset($post['user_name']) && $map[] = ['user_name', 'like', '%' . $post['user_name'] . '%'];
        //排行数据 体现，充值，余额
        $order = [];
        if (isset($post['name']) && isset($post['sort'])) $order = $post['name'] . ' ' . $post['sort'];
        isset($post['is_fictitious']) && $map[] = ['is_fictitious', '=', $post['is_fictitious']];

        //获取用户能够查询的 用户列表 为空是查询所有
        $userAll = $this->get_user_auth($this->request->admin_user);
        $list = $this->model->user_sort($userAll, $map, $order, $limit, $page);
         $this->success($list);
    }
}
