<?php


namespace app\controller\auth;

use app\controller\Base;


use app\model\ActionModel as models;
use think\exception\ValidateException;
use \app\validate\Action as MenuV;

class Action extends Base
{
    protected $model;

    /**
     * api控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件

        $list = $this->model
            ->order('id asc')
            ->paginate(['list_rows' => $limit, 'page' => $page]);
         $this->success($list);
    }

    /**
     * 菜单添加
     */
    public function add()
    {
        //过滤数据
        $postField = 'title,path';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //验证数据
        try {
            validate(MenuV::class)->scene('add')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
             $this->failed($e->getError());
        }

        //验证成功，查询是否存在该用户
        $user = $this->model->where('title', $post['title'])->find();
        if ($user)  $this->failed('该菜单以存在');

        $post['status'] = isset($post['status']) ? $post['status'] : 1;

        $post['admin_uid'] = session('admin_user.id');
        $save = $this->model->save($post);
        if ($save)  $this->success([]);
         $this->failed('新增失败');
    }

    /**
     * 菜单查询
     * @return mixed
     */
    public function detail()
    {
        //过滤数据
        $postField = 'id';
        $post = $this->request->only(explode(',', $postField), 'post', null);
        //验证数据
        try {
            validate(MenuV::class)->scene('detail')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
             $this->failed($e->getError());
        }
        //查询用户数据
        $user = $this->model->find($post['id']);
        if ($user)  $this->success($user);
         $this->failed('菜单不存在');
    }

    /**
     * 菜单修改
     * @return mixed
     */
    public function edit()
    {
        //过滤数据
        $postField = 'id,pid,title,status,path,icon';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        //验证数据
        try {
            validate(MenuV::class)->scene('edit')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
             $this->failed($e->getError());
        }

        //查询是否重复的该菜单
        $find = $this->model->where('title', $post['title'])->where('id', '<>', $post['id'])->find();
        if ($find)  $this->failed('该菜单以存在');

        $post['admin_uid'] = session('admin_user.id');
        //执行修改数据
        $save = $this->model->update($post);
        if ($save)  $this->success([]);
         $this->failed('修改失败');
    }
}