<?php


namespace app\controller\auth;

use app\controller\Base;

use app\model\AdminRole as models;
use think\exception\ValidateException;
use \app\validate\AdminRole as validates;

class Role extends Base
{
    protected $model;

    /**
     * 角色控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 20);
        //查询搜索条件
        $list = $this->model->page_list($limit, $page);
        $this->success($list);
    }

    /**
     * 添加
     */
    public function add()
    {
        //过滤数据
        $postField = 'name,status';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        //验证数据
        try {
            validate(validates::class)->scene('add')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            $this->failed($e->getError());
        }

        $user = $this->model->where('name', $post['name'])->find();
        if ($user) $this->failed('该角色以存在');

        $post['status'] = isset($post['status']) ?? 1;
        $save = $this->model->save($post);

        if ($save) $this->success([]);
        $this->failed('新增失败');
    }

    /**
     * 修改
     * @return mixed
     */
    public function edit()
    {
        //过滤数据
        $postField = 'id,name,status';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        //验证数据
        try {
            validate(validates::class)->scene('edit')->check($post);
        } catch (ValidateException $e) {
            // 验证失败 输出错误信息
            $this->failed($e->getError());
        }

        //查询是否重复的该菜单
        $find = $this->model->where('name', $post['name'])->where('id', '<>', $post['id'])->find();
        if ($find) $this->failed('该角色以存在');

        //执行修改数据
        $save = $this->model->update($post);
        if ($save) $this->success([]);
        $this->failed('修改失败');
    }
}